export const CouponData = [
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Ongoing",
    color: "Blue",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Expired",
    Color: "Red",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Hold",
    Color: "Orange",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Ongoing",
    Color: "Green",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Expired",
    Color: "Red",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Hold",
    Color: "Blue",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Ongoing",
    Color: "Green",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Expired",
    Color: "Orange",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Hold",
    Color: "Red",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Ongoing",
    Color: "Blue",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Expired",
    Color: "Green",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Hold",
    Color: "Orange",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Ongoing",
    Color: "Red",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Expired",
    Color: "Blue",
  },
  {
    Name: "Coupon Code",
    Code: "KJSYGHDF",
    Details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quis a, magna ante id libero eleifend consectetur. Odio nibh fringilla sit varius ut orci libero. Posuere sed sit turpis ac congue viverra. ",
    ExpireDate: "02/05/21",
    CutOffPc: "25%",
    Value: "500.00",
    StartingDate: "12-02-21 ",
    StartingTime: "04:30am",
    ExpireTime: "04:30am",
    NoOfUser: "5",
    Status: "Hold",
    Color: "Orange",
  },
];
