export const NotificationItem = [
  {
    id: "1",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "2",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "3",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "4",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "5",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "6",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "7",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "8",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "9",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "10",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
  {
    id: "11",
    Photo: "",
    ProductName: "akshjdg",
    Status: "akshgd",
    Time: "kajsdh",
  },
];
