export const AllPaymentData = [
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    GST: "200",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    GST: "200",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    GST: "200",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    GST: "200",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    GST: "200",
    Status: "Ongoing",
    Total: "5000",
  },
];
