export const RecivedData = [
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment Recived",
    Date: "15-14-21",
    Status: "Recived",
    Total: "5000",
  },
];
