export const SentData = [
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Ongoing",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Sent",
    Total: "5000",
  },
  {
    TransactionId: "JKHGLKGJASDKJH",
    Name: "Payment made to emagz",
    Date: "15-14-21",
    Status: "Ongoing",
    Total: "5000",
  },
];
