export const AllOrder = [
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Cancled",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Delivery",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
];
