export const DeliveredItems = [
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Delivered",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Delivered",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Delivered",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Delivered",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Dispatch",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Delivered",
  },
];
