export const PendingItems = [
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
  {
    ProductId: "HDGASHDJHSD",
    ProductName: "asdasd",
    Qty: 1,
    GST: 200,
    Total: 500,
    Status: "Pending",
  },
];
